config/routes.rb
GhArchive::Application.routes.draw do
  resources :fetches, only: [:new, :create]
  resources :events, only: [:new, :create, :index]

end

app/models/event.rb
require 'open-uri'
require 'zlib'
require 'yajl'

class Event < ActiveRecord::Base
  belongs_to :fetch
  belongs_to :report

  def parse_url(url)
    gz = open(url)
    js = Zlib::GzipReader.new(gz).read

    Yajl::Parser.parse(js) do |event|
      print event
    end
  end
end

app/models/fetch.rb
class Fetch < ActiveRecord::Base
  has_many :events

end

app/models/report.rb
class Report < ActiveRecord::Base
  has_many :events
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception
end

app/controllers/events_controller.rb
class EventsController < ApplicationController
  def index
    @events = Event.all
  end

  def new
  end

  def create
  end
end

app/controllers/fetches_controller.rb
class FetchesController < ApplicationController
  def new
  end

  def create
    @fetch = Fetch.new(fetch_params)
    @fetch.save

    redirect_to new_fetch_path
  end

  private
    def fetch_params
      params.require(:fetch).permit(:url)
    end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/events_helper.rb
module EventsHelper
end

app/helpers/fetches_helper.rb
module FetchesHelper
end

app/views/events/create.html.erb
<h1>Events#create</h1>
<p>Find me in app/views/events/create.html.erb</p>

app/views/events/index.html.erb
<h1>Events#index</h1>
<p>Find me in app/views/events/index.html.erb</p>

app/views/events/new.html.erb
<h1>Events#new</h1>
<p>Find me in app/views/events/new.html.erb</p>

app/views/fetches/new.html.erb
<h1>Fetch GitHub Archive</h1>

<%= form_for :fetch, url: fetches_path do |f| %>
  <p>
    <%= f.label :url %>
    <%= f.text_field :url %>
  </p>

  <p>
    <%= f.submit %>
  </p>
<% end %>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>GhArchive</title>
  <%= stylesheet_link_tag    "application", media: "all", "data-turbolinks-track" => true %>
  <%= javascript_include_tag "application", "data-turbolinks-track" => true %>
  <%= csrf_meta_tags %>
</head>
<body>

<%= yield %>

</body>
</html>